### ISSUE TITLE
Android sürümü

### ISSUE THREAD

**Issue by fstasel** [CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player#1]
LR ve SRS dokümanında projenin Android sürümüne ait herhangi bir araştırma ya da açıklama henüz eklenmemiş. Kısa zamanda ekleyelim.

**Comment by utkuy-ceng** [comment]
LR dökümanına araştırma eklendi, SRS kısmına da en yakın zamanda eklenip sayfa güncellenecek.
Tahmini SRS güncellenme tarihi: 20 Aralık 2021
