### ISSUE TITLE
Project Poster Design

### ISSUE THREAD

**Issue by ayhanarici** [CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player#10]
@heisanengineer Please redesign the poster according to correct dimensions and share it on wiki page.

**Comment by heisanengineer** [comment]
Hello @ayhanarici, I designed the proctor poster and update our wiki page.

if you want, you can download the poster at this [link](https://github.com/CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player/blob/main/docs/ProjectPoster.png) or you can view check our [wiki page](https://github.com/CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player/wiki/Project-Poster).

<img width="525" alt="AMPPoster" src="https://user-images.githubusercontent.com/93338158/170594609-7498da81-7c5a-4b3e-9cc8-604daf001a8e.png">

**Comment by heisanengineer** [comment]
Hey @ayhanarıcı, I am sending you the latest and ready-to-print preview version again.


<img width="763" alt="PosterPrev" src="https://user-images.githubusercontent.com/93338158/170828057-b661d66d-aa68-4ee0-beda-5f9448a00063.png">
