### ISSUE TITLE
Project Poster Print

### ISSUE THREAD

**Issue by ayhanarici** [CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player#11]
@sunshinelif Please get the printed version of our new project poster.

**Comment by heisanengineer** [comment]
Hey @ayhanarici  & @sunshinelif  Do not forget that the poster design that needs to be printed is in this [Poster Link](https://github.com/CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player/tree/main/docs/ProjectPoster).

**Comment by sunshinelif** [comment]
Poster design printed and delivered to the department.
