### ISSUE TITLE
New User Interface Design 

### ISSUE THREAD

**Issue by ayhanarici** [CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player#2]
Dear @heisanengineer ,
Can you design and upload new UI templates in QtDesigner for the project we are developing?
Thanks.

**Comment by heisanengineer** [comment]
- [x] @ayhanarici Photoshop designs of the User Interface are ready and I have uploaded them to the Graphic Interface Design folder in test folder. 
- [ ] I will design UI on QtDesigner and add the .ui files in Graphic Interface Design folder as soon as possible.

Here you can follow my confirmation of the checkbox.

Best regards.

**Comment by ayhanarici** [comment]
@heisanengineer ,
Best regards.
