### ISSUE TITLE
Test Plan

### ISSUE THREAD

**Issue by ayhanarici** [CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player#4]
Hi @heisanengineer and @utkuy-ceng ,
Could you add the first version of the Test Plan we prepared to our wiki page and make the necessary arrangements?
Best regards.

**Comment by heisanengineer** [comment]
Our [Test Plan](https://github.com/CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player/wiki/Test-Plan) page is available.

I added the v1 version we prepared to the page. Detailed Test Cases part will be organized by @utkuy-ceng .

Best Regards.

**Comment by utkuy-ceng** [comment]
Detailed Test Cases has been organized. Can close issue.
Regards
