### ISSUE TITLE
Work Plan For 408

### ISSUE THREAD

**Issue by heisanengineer** [CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player#5]
I created a template for the Work plan. With SRS/SDD, TEST PLAN DOCUMENT, SOFTWARE PRODUCT, USER MANUAL, MATERIALS, PRESENTATION headers. Can I get the dates that should be shown in the work plan and the names of the people who will do the work? 

In summary: I can finish this job if I get the detail information.

@utkuy-ceng

**Comment by utkuy-ceng** [comment]
21 February 25 March : SRS/SDD
Work Plan 21 February 27 February
SRS 27 February 5 March
SDD March 5th March 12th
Data 12 March 17 March
Algorithm Tests 17 March 25 March
Github & Wiki Implementations March 9 March 25

25 March 1 April : Test Plan
Abstract - Intro March 25 - April 1
Github wiki implementation March 28 April 1 April


April 22 - May 10 : User Manual
Implementation : 22 April - 1 May
github wiki may 1 - may 10


25 March - 3 June: Materials
Project Test Plan 25 March - 1 April
Project Report May 10 - May 27
Test Results : May 1 - May 10
Project Poster May 27 - June 3
Update Webpage: 27 May - 3 June
Demo Video : June 3 - June 13
Wiki implementation : May 10 - June 13

Regards.
