### ISSUE TITLE
AboutUs python file and content should be changed

### ISSUE THREAD

**Issue by utkuy-ceng** [CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player#8]
We need to clarify the users/customers about who we are and what are we doing. Please improve and share the aboutus.py file at repository.

**Comment by sunshinelif** [comment]
Preparing the content of about us, @ayhanarici will import it into aboutus.ui file

**Comment by ayhanarici** [comment]
File has been updated with the content you've sent before and imported into aboutus.ui. If you change anything, reopen this issue
