### ISSUE TITLE
Release version update

### ISSUE THREAD

**Issue by sunshinelif** [CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player#9]
Hey @heisanengineer can you update the tar.gz and rar versions of new release exe file?
Regards.

**Comment by heisanengineer** [comment]
Hey @sunshinelif I updated the newly released exe file and tar.gz / rar versions.

I'm attaching the link if you want to check it out.

https://github.com/CankayaUniversity/ceng-407-408-2021-2022-Ambilight-Media-Player/releases/tag/v1.0

Kind regards.
